version: "3.6"
services:
  guestbook-php:
    build: guestbook-php
    depends_on:
    - redis-master
    deploy:
      replicas: ${guestbook-php.replicas}
    image: docker.io/sixeyed/guestbook-php
    ports:
    - ${guestbook-php.port}:80
  redis-follower:
    depends_on:
    - redis-master
    deploy:
      replicas: ${redis-follower.replicas}
    image: gcr.io/google_samples/gb-redisslave:v1
  redis-master:
    image: k8s.gcr.io/redis:e2e
