name: Create GKE cluster

on:
  push:
    paths:
      - '.github/workflows/gcp-create-*.yaml'

jobs:
  initialize: 
    runs-on: ubuntu-latest
 
    steps:
    - uses: 'docker://sixeyed/gcp-create-gke:latest'
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SA_KEY_ENCODED: ${{ secrets.GCP_SA_KEY_ENCODED }}
        GCP_ZONE: ${{ secrets.GCP_ZONE }}
        GKE_CLUSTER_TEMPLATE: 
        GKE_KUBE_VERSION: 1.13.7-gke.8
        GKE_NODE_COUNT: 2